name: gradus
description: "Build your story - day by day"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  flutter_bloc: ^9.1.1
  # Functional Programming
  dartz: ^0.10.1
  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # Firebase
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1
  # Utils
  uuid: ^4.5.1
  equatable: ^2.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  build_runner: ^2.5.2
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
